name: Code Review GPT

on:
  pull_request:
    branches: [main]

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run code review script
        run: bun run start review --ci=github --provider=azureai
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_SHA: ${{ github.sha }}
          AZURE_OPENAI_API_INSTANCE_NAME: "azo-ai-gpt"
          AZURE_OPENAI_API_DEPLOYMENT_NAME: "gpt-40"
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_VERSION: "2024-10-01-preview"

      # - name: Code Review GPT
      #   uses: mattzcarey/code-review-gpt@v0.1.11
      #   with:
      #     GITHUB_TOKEN: ${{ github.token }}
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     MODEL: "gpt-4o"
      #     REVIEW_LANGUAGE: "English"
      # - name: Install Bun
      #   run: curl -fsSL https://bun.sh/install | bash
