name: 'Create Issue on Release PR'

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  create-issue:
    if: startsWith(github.head_ref, 'release-please--branches--main--components--root')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'releases/'"
      - uses: actions/checkout@v4
      - name: Create Issue
        uses: actions-ecosystem/action-create-issue@v1
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "New issue for PR: ${{ github.ref }}"
          body: "This issue is automatically created for the following release pull request. Please review the changes in the release."
